<?php 

/**
 * @file
 * Provide structure for the administrative interface to Views.
 */

function silky_wysiwyg_include_directory($type) 
{
  switch($type) {
    case 'plugins':
      return $type;
  }
}

function flatten_array(array $array) 
{
    $flattened_array = array();
    array_walk_recursive($array, function($a) use (&$flattened_array) { $flattened_array[] = $a; });
    return $flattened_array;
}

function default_buttons()
{
  $default_buttons = array(
    'default' => array(
      'Bold',
      'Italic',
      'Underline',
      'JustifyLeft',
      'JustifyCenter',
      'JustifyRight',
      'BulletedList',
      'NumberedList',
      'Link',
      'Unlink',
      'Blockquote',
      'Source',
      'Copy',
      'Paste',
      'Table',
      'PasteFromWord',
      'Format',
      'Styles',
    ),
    'custom' => array(
      'media',
      'accordion_wrapper',
      'accordion_header',
      'accordion_content',
      'tabs_wrapper',
      'tab_wrapper',
      'tab_header',
    )
  );

  return $default_buttons;
}


/**
 * Set default buttons on wysiwyg profile.
 *
 * To unset buttons remove from $default_buttons array.
 *
 * @see hook_form_FORM_ID_form_alter()
 *
 */
function silky_form_wysiwyg_profile_form_alter(&$form, $form_state, $form_id)
{
  
  $default_buttons = default_buttons();
  
  foreach($default_buttons['default'] as $button_value)
  {
    $form['buttons']['default'][$button_value]['#default_value'] = 1;
  }
  
  foreach($default_buttons['custom'] as $button_value)
  {
    $form['buttons']['drupal'][$button_value]['#default_value'] = 1;
  }
  
  $form['css']['css_path']['#default_value'] = 'sites/all/modules/silky/plugins/snippet.css';
  

}

function silky_wysiwyg_editor_settings_alter(&$settings, $context)
{
  
  if ($context['profile']->editor == 'ckeditor') {
    
    //Buttons
    $settings['toolbar'] = array(flatten_array(default_buttons()));
    //Set up module CSS
    $settings['contentsCss'] = array('sites/all/modules/silky/plugins/snippet.css');

  }
}